module.exports = {
    plugins: [
        'unicorn'
    ],
    rules: {
        // Undocumented
        'array-callback-return': 'error',
        'block-scoped-var': 'error',
        'complexity': 'off',
        'curly': 'error',
        'default-case': 'error',
        'dot-location': [
            'error',
            'property',
        ],
        'dot-notation': 'error',
        'eqeqeq': 'error',
        'for-direction': 'error',
        'getter-return': 'error',
        'no-alert': 'error',
        'no-async-promise-executor': 'error',
        'no-caller': 'error',
        'no-case-declarations': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-console': 'error',
        'no-constant-condition': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-dupe-args': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-empty-character-class': 'error',
        'no-empty': 'error',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'error',
        'no-extra-semi': 'error',
        'no-func-assign': 'error',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-misleading-character-class': 'error',
        'no-obj-calls': 'error',
        'no-prototype-builtins': 'error',
        'no-regex-spaces': 'error',
        'no-sparse-arrays': 'error',
        'no-unexpected-multiline': 'error',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'require-atomic-updates': 'error',
        'unicorn/prefer-flat-map': 'error',
        'use-isnan': 'error',
        'valid-typeof': 'error',

        // Evaluting
        'class-methods-use-this': 'error',
        'guard-for-in': 'error',
        'max-classes-per-file': 'error',
        'no-await-in-loop': 'error',
        'no-extra-parens': 'off',
        'no-template-curly-in-string': 'error',
    }
};
