const undocumented = {
    "array-bracket-newline": [
        "error",
        {
            "minItems": 2,
        },
    ],
    "array-bracket-spacing": "error",
    "array-callback-return": "error",
    "array-element-newline": [
        "error",
        "always",
    ],
    "arrow-body-style": [
        "error",
        "always",
    ],
    "arrow-parens": "error",
    "arrow-spacing": "error",
    "block-scoped-var": "error",
    "block-spacing": "error",
    "callback-return": "error",
    "capitalized-comments": "error",
    "comma-dangle": [
        "error",
        "always-multiline",
    ],
    "comma-spacing": "error",
    "comma-style": "error",
    "complexity": "off",
    "computed-property-spacing": "error",
    "constructor-super": "error",
    "curly": "error",
    "default-case": "error",
    "dot-location": [
        "error",
        "property",
    ],
    "dot-notation": "error",
    "eol-last": "error",
    "eqeqeq": "error",
    "for-direction": "error",
    "func-call-spacing": "error",
    "generator-star-spacing": "error",
    "getter-return": "error",
    "global-require": "error",
    "handle-callback-err": [
        "error",
        "^(err|error)$",
    ],
    "indent": "error",
    "init-declarations": "off",
    "jsx-quotes": "error",
    "key-spacing": "error",
    "keyword-spacing": "error",
    "line-comment-position": "error",
    "linebreak-style": "error",
    "lines-between-class-members": "error",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-params": "off",
    "max-statements": "off",
    "multiline-comment-style": [
        "error",
        "separate-lines",
    ],
    "no-alert": "error",
    "no-async-promise-executor": "error",
    "no-buffer-constructor": "error",
    "no-caller": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-console": "error",
    "no-const-assign": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-div-regex": "error",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-duplicate-imports": "error",
    "no-else-return": [
        "error",
        {
            "allowElseIf": false,
        },
    ],
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-function": "error",
    "no-empty-pattern": "error",
    "no-eval": "error",
    "no-ex-assign": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-boolean-cast": "error",
    "no-extra-semi": "error",
    "no-fallthrough": "error",
    "no-floating-decimal": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-inner-declarations": "error",
    "no-invalid-regexp": "error",
    "no-invalid-this": "error",
    "no-irregular-whitespace": "error",
    "no-iterator": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-loop-func": "error",
    "no-misleading-character-class": "error",
    "no-multi-spaces": "error",
    "no-multi-str": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-object": "error",
    "no-new-require": "error",
    "no-obj-calls": "error",
    "no-octal": "error",
    "no-octal-escape": "error",
    "no-param-reassign": "error",
    "no-path-concat": "error",
    "no-plusplus": "error",
    "no-process-env": "error",
    "no-proto": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-return-assign": "error",
    "no-return-await": "error",
    "no-script-url": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-sync": "error",
    "no-tabs": "error",
    "no-ternary": "error",
    "no-this-before-super": "error",
    "no-throw-literal": "error",
    "no-trailing-spaces": "error",
    "no-undef": "error",
    "no-undef-init": "error",
    "no-undefined": "error",
    "no-unexpected-multiline": "error",
    "no-unmodified-loop-condition": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unused-vars": "error",
    "no-use-before-define": "error",
    "no-useless-call": "error",
    "no-useless-catch": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "error",
    "no-useless-constructor": "error",
    "no-useless-escape": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-void": "error",
    "no-warning-comments": "warn",
    "no-whitespace-before-property": "error",
    "no-with": "error",
    "object-curly-newline": [
        "error",
        {
            "minProperties": 1,
        },
    ],
    "object-property-newline": "error",
    "one-var": [
        "error",
        "never",
    ],
    "one-var-declaration-per-line": "error",
    "operator-assignment": "error",
    "operator-linebreak": [
        "error",
        "before",
    ],
    "padded-blocks": [
        "error",
        "never",
    ],
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-named-capture-group": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "quotes": "error",
    "radix": "error",
    "require-atomic-updates": "error",
    "require-await": "error",
    "require-unicode-regexp": "error",
    "require-yield": "error",
    "rest-spread-spacing": "error",
    "semi": "error",
    "semi-spacing": "error",
    "semi-style": "error",
    "sort-imports": "off",
    "space-before-blocks": "error",
    "space-before-function-paren": [
        "error",
        "never",
    ],
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": "error",
    "strict": "error",
    "switch-colon-spacing": "error",
    "symbol-description": "error",
    "template-curly-spacing": "error",
    "template-tag-spacing": "error",
    "unicode-bom": "error",
    "unicorn/catch-error-name": "error",
    "unicorn/custom-error-definition": "error",
    "unicorn/error-message": "error",
    "unicorn/escape-case": "error",
    "unicorn/explicit-length-check": "error",
    "unicorn/filename-case": "error",
    "unicorn/import-index": "error",
    "unicorn/new-for-builtins": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-array-instanceof": "error",
    "unicorn/no-console-spaces": "error",
    "unicorn/no-fn-reference-in-iterator": "error",
    "unicorn/no-for-loop": "error",
    "unicorn/no-hex-escape": "error",
    // TODO: "unicorn/no-keyword-prefix": "error",
    "unicorn/no-process-exit": "error",
    "unicorn/no-unreadable-array-destructuring": "error",
    "unicorn/no-unsafe-regex": "off",
    "unicorn/no-unused-properties": "error",
    "unicorn/no-zero-fractions": "error",
    "unicorn/number-literal-case": "error",
    "unicorn/prefer-exponentiation-operator": "error",
    "unicorn/prefer-flat-map": "error",
    "unicorn/prefer-includes": "error",
    "unicorn/prefer-spread": "error",
    "unicorn/prefer-starts-ends-with": "error",
    "unicorn/prefer-type-error": "error",
    "unicorn/regex-shorthand": "error",
    "unicorn/throw-new-error": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "vars-on-top": "off",
    "wrap-regex": "off",
    "yield-star-spacing": "error",
    "yoda": "error",
};

// Rules possibly redundant because of more restrictive rules
const redundant = {
    "consistent-this": "error",

    "implicit-arrow-linebreak": "error",

    // Covered by `no-ternary`
    "multiline-ternary": [
        "error",
        "always-multiline",
    ],

    // Covered by `arrow-body-style`
    "no-confusing-arrow": "off",

    // Covered by `eqeqeq`
    "no-eq-null": "error",

    // Covered by `no-labels`
    "no-extra-label": "error",

    // Covered by `no-labels`, `no-var`
    "no-label-var": "error",

    "no-mixed-requires": "error",

    // Covered by `unicorn/new-for-builtins`
    "no-new-symbol": "error",

    // Covered by `unicorn/new-for-builtins`
    "no-new-wrappers": "error",

    // Covered by `unicorn/no-process-exit`
    "no-process-exit": "off",

    // Covered by `no-ternary`
    "no-unneeded-ternary": "error",

    // Covered by `no-labels`
    "no-unused-labels": "error",

    "nonblock-statement-body-position": "error",

    // Covered by `object-curly-newline`
    "object-curly-spacing": "error",

    // Covered by `no-var`
    "sort-vars": "off",
};

// Rules that may be removed or reconfigured
const evalutating = {
    "brace-style": "error",
    "camelcase": "error",
    "class-methods-use-this": "error",
    "func-name-matching": "error",
    "func-names": "error",
    "func-style": "error",
    "function-paren-newline": [
        "error",
        {
            "minItems": 2,
        },
    ],
    "guard-for-in": "error",
    "id-length": "error",
    "lines-around-comment": "error",
    "max-classes-per-file": "error",
    "max-depth": "warn",
    "max-len": "warn",
    "max-statements-per-line": "error",
    "no-await-in-loop": "error",
    "no-extra-parens": "off",
    "no-implicit-coercion": "error",
    "no-magic-numbers": [
        "error",
        {
            "detectObjects": true,
            "enforceConst": true,
            "ignore": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
            ],
            "ignoreArrayIndexes": true,
        },
    ],
    "no-template-curly-in-string": "error",
    "no-underscore-dangle": "error",
    "no-unused-expressions": "error",
    "object-shorthand": "error",
    "prefer-destructuring": "error",
    "quote-props": "error",
    "sort-keys": "error",
    "unicorn/prevent-abbreviations": "error",
    "wrap-iife": "error",
};

// eslint-disable-next-line no-undef
module.exports = {
    "plugins": ["unicorn"],
    "rules": {
        ...undocumented,
        ...redundant,
        ...evalutating,
    },
};
